#!/usr/bin/env sh

set -eu

# For running foreign-arch target binaries under qemu-user
# (binfmt_misc). Both are inert when running native binaries, and they
# are inherited by every spawned child process.
#
# QEMU_LD_PREFIX: our cross-built binaries embed the canonical ELF
#   interpreter path (e.g. /lib/ld-linux-aarch64.so.1); qemu resolves
#   it against this prefix to find it in the cross toolchain sysroot.
# QEMU_RESERVED_VA: qemu pre-allocates a private guest virtual address
#   region, which keeps brk growing like on native Linux. without it
#   the guest ld.so loads us into the mmap area where the break cannot
#   grow anymore.
export QEMU_LD_PREFIX="${QEMU_LD_PREFIX:-/usr/aarch64-linux-gnu}"
export QEMU_RESERVED_VA="${QEMU_RESERVED_VA:-4G}"

PREVIOUS_STAGE_BACKEND="-llvm"
PREVIOUS_STAGE="maru.10"
BUILD="build"
HOST_DIR="$BUILD/$PREVIOUS_STAGE"

ensure_host_binary() {
    if [ ! -e "$HOST_DIR/eval" ]; then
        echo "build.sh is building the host..."

        mkdir -p "$BUILD"

        # After cloning, create the local branch ourselves.
        # See: https://stackoverflow.com/questions/40310932/git-hub-clone-all-branches-at-once
        if ! git show-ref --verify --quiet "refs/heads/$PREVIOUS_STAGE"; then
            git branch --quiet --track \
                "$PREVIOUS_STAGE" \
                "remotes/origin/$PREVIOUS_STAGE"
        fi

        if [ ! -d "$HOST_DIR" ]; then
            git worktree add --detach --force \
                "$HOST_DIR" \
                "$PREVIOUS_STAGE"
        fi

        # Git checkout does not update file modification times, so touch
        # everything checked in under build/.
        if [ -d "${HOST_DIR}/${BUILD}" ]; then
            find "${HOST_DIR}/${BUILD}" -type f -exec touch {} +
            # that file is generated by stage n-1 (and checked into
            # the repo), so if we want to avoid recursing, then we
            # must make sure that the file is newer than its
            # dependencies.
            touch "${HOST_DIR}/source/c/cgrov.g.l"
        fi

        make --directory="$HOST_DIR" PLATFORM=posix "eval${PREVIOUS_STAGE_BACKEND}"
    fi
}

ensure_host_binary

echo "Calling build.l"

exec "$HOST_DIR/eval" boot.l build.l "$@"
