# podman build --platform linux/amd64 -t maru -f Dockerfile.dev .
# podman run  --tty --rm --interactive --volume "$(pwd)":/workspace --workdir /workspace maru /bin/bash

FROM docker.io/debian:unstable

ENV DEBIAN_FRONTEND=noninteractive

ARG TARGETARCH

RUN echo TARGETARCH="$TARGETARCH"

RUN sed -i 's/Components: main$/Components: main contrib/' /etc/apt/sources.list.d/debian.sources && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        bash \
        make \
        llvm \
        clang \
        libc6-dev \
        libffi-dev \
        gdb \
        git \
        time \
        ca-certificates \
        less \
        bash-completion \
        nano \
    # Conditional packages for x86
    && if [ "$TARGETARCH" = "amd64" ]; then \
      dpkg --add-architecture i386 && \
        apt-get update && \
        apt-get install -y --no-install-recommends libc6-dev-i386 gcc-multilib; \
    fi \
    && rm -rf /var/lib/apt/lists/*

# Ensure bash is the default shell
# SHELL ["/bin/bash", "-c"]

RUN update-alternatives --install /usr/bin/clang clang /usr/bin/clang-21 100 && \
    update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-21 100

# Enable bash-completion for root
RUN echo 'if [ -f /usr/share/bash-completion/bash_completion ]; then' >> /root/.bashrc \
 && echo '  . /usr/share/bash-completion/bash_completion' >> /root/.bashrc \
 && echo 'fi' >> /root/.bashrc >> /root/.bashrc

# This is needed to avoid a git warning:
# fatal: detected dubious ownership in repository at '/workspace'
RUN git config --global --add safe.directory /workspace

WORKDIR /workspace
