# podman build --platform linux/amd64 -t ghcr.io/attila-lendvai/maru-ci:amd64 --build-arg CI_IMAGE_VERSION=$(date --rfc-3339 date) -f Dockerfile.ci .
# podman build --platform linux/arm64 -t ghcr.io/attila-lendvai/maru-ci:arm64 --build-arg CI_IMAGE_VERSION=$(date --rfc-3339 date) -f Dockerfile.ci .

# need to log in with a token generated at: https://github.com/settings/tokens
# podman login ghcr.io -u attila-lendvai

# podman push ghcr.io/attila-lendvai/maru-ci:amd64
# podman push ghcr.io/attila-lendvai/maru-ci:arm64

# for the first time go to:
# https://github.com/attila-lendvai?tab=packages&ecosystem=container
# and make it public in the package settings

FROM docker.io/ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

ARG TARGETARCH

ARG CI_IMAGE_VERSION=dev
ENV CI_IMAGE_VERSION=$CI_IMAGE_VERSION

RUN echo TARGETARCH="$TARGETARCH"
RUN echo CI_IMAGE_VERSION="$CI_IMAGE_VERSION"

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        bash \
        make \
        llvm \
        clang-20 \
        libc6-dev \
        libffi-dev \
        binutils-aarch64-linux-gnu \
        binutils-x86-64-linux-gnu \
        git \
        time \
        lsb-release software-properties-common gnupg \
        wget \
        curl \
        ca-certificates \
        musl \
        musl-dev \
    # Conditional packages for x86
    && if [ "$TARGETARCH" = "amd64" ]; then \
      dpkg --add-architecture i386 && \
        apt-get update && \
        apt-get install -y --no-install-recommends libc6-dev-i386 gcc-multilib; \
    fi \
    && rm -rf /var/lib/apt/lists/*

# if/when we need the latest llvm...
# RUN curl -fsSL https://apt.llvm.org/llvm.sh -o llvm.sh && chmod +x llvm.sh && ./llvm.sh 23

# Ensure bash is the default shell
# SHELL ["/bin/bash", "-c"]

RUN update-alternatives --install /usr/bin/clang clang /usr/bin/clang-20 100 && \
    update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-20 100 && \
    update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100 && \
    update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100

WORKDIR /workspace
