name: CI

on:
  push:
    branches:
      - maru.10
      - staging
  pull_request:
    branches:
      - maru.10

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/attila-lendvai/maru-ci:latest
      options: --init

    steps:
      - name: Calm down Git
        run: git config --global --add safe.directory /__w/maru/maru

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run:  make PLATFORM=libc  test-bootstrap
      - run:  make PLATFORM=linux test-bootstrap

      - run:  make PROFILER=1 PLATFORM=libc  test-bootstrap

      - run:  make test-evaluator
      - run:  make test-parser

      - run:  make PLATFORM=linux test-elf-llvm
      - run:  make PLATFORM=linux test-elf-x86
