name: CI

on:
  push:
    branches:
      - maru.10
      - staging
    paths-ignore:
      - '**.md'
      - 'doc/**'

  pull_request:
    branches:
      - maru.10
    paths-ignore:
      - '**.md'
      - 'doc/**'

jobs:
  build-linux-amd64:
    name: "linux x86_64"
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/attila-lendvai/maru-ci:amd64
      options: --init

    steps:
      - name: System info
        run: |
          echo "===== OS Info ====="
          uname -a
          sw_vers || lsb_release -a || cat /etc/os-release || true
          echo "===== CPU Info ====="
          uname -m
          sysctl -n machdep.cpu.brand_string || lscpu || true
          echo "===== Environment ====="
          env

      - name: Calm down Git
        run: git config --global --add safe.directory /__w/maru/maru

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false

      - run:  clang --version && cc --version

      - run:  timeout 5m make PLATFORM=libc  test-bootstrap
      - run:  timeout 5m make PLATFORM=posix test-bootstrap
      - run:  timeout 5m make PLATFORM=linux test-bootstrap
      - run:  timeout 5m make TARGET_CPU=i686 PLATFORM=libc  test-bootstrap
      - run:  timeout 5m make TARGET_CPU=i686 PLATFORM=posix test-bootstrap
      - run:  timeout 5m make TARGET_CPU=i686 PLATFORM=linux test-bootstrap

      - run:  timeout 5m make PROFILER=1 PLATFORM=libc  test-bootstrap

      - run:  timeout 5m make test-evaluator
      - run:  timeout 5m make test-parser

      - run:  timeout 5m make PLATFORM=posix test-elf
      - run:  timeout 5m make PLATFORM=linux test-elf

      - run:  timeout 5m make PLATFORM=posix test-jit
      - run:  timeout 5m make PLATFORM=linux test-jit

  build-linux-arm64:
    name: "linux aarch64"
    runs-on: ubuntu-24.04-arm
    container:
      image: ghcr.io/attila-lendvai/maru-ci:arm64
      options: --init

    steps:
      - name: System info
        run: |
          echo "===== OS Info ====="
          uname -a
          sw_vers || lsb_release -a || cat /etc/os-release || true
          echo "===== CPU Info ====="
          uname -m
          sysctl -n machdep.cpu.brand_string || lscpu || true
          echo "===== Environment ====="
          env

      - name: Calm down Git
        run: git config --global --add safe.directory /__w/maru/maru

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false

      - run:  clang --version && cc --version

      - run:  timeout 5m make PLATFORM=libc  test-bootstrap-llvm
      - run:  timeout 5m make PLATFORM=posix test-bootstrap-llvm
      - run:  timeout 5m make PLATFORM=linux test-bootstrap-llvm

      - run:  timeout 5m make PROFILER=1 PLATFORM=libc  test-bootstrap-llvm
      - run:  timeout 5m make PROFILER=1 PLATFORM=posix test-bootstrap-llvm

      - run:  timeout 5m make test-evaluator
      - run:  timeout 5m make test-parser

  build-darwin:
    name: "darwin aarch64 (errors ignored)"
    runs-on: macos-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: System info
        run: |
          echo "===== OS Info ====="
          uname -a
          sw_vers || lsb_release -a || cat /etc/os-release || true
          echo "===== CPU Info ====="
          uname -m
          sysctl -n machdep.cpu.brand_string || lscpu || true
          echo "===== Environment ====="
          env

      - name: Calm down Git
        run: git config --global --add safe.directory /__w/maru/maru

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false

      - name: Install clang
        # this action caches the archives, but not the install
        # itself. it's simpler this way, but it takes about a minute.
        uses: gerlero/brew-install@v1
        with:
          packages: llvm coreutils

      # - name: Cache Homebrew packages
      #   uses: actions/cache@v4
      #   with:
      #     # Paths to cache:
      #     # /usr/local/Homebrew - installation folder of Homebrew
      #     # /usr/local/Cellar - installation folder of Homebrew formulae
      #     # /usr/local/Frameworks, /usr/local/bin, /usr/local/opt - contain (links to) binaries installed by Homebrew formulae
      #     # /usr/local/lib/python3.12 - Python3 packages installation
      #     # /opt/homebrew - Apple Silicon path
      #     path: |
      #       /usr/local/Homebrew
      #       /usr/local/Cellar
      #       /usr/local/Frameworks
      #       /usr/local/bin
      #       /usr/local/opt
      #       /opt/homebrew

      #     key: macos-build-cache-${{ hashFiles('**/Brewfile') }}
      #     restore-keys: macos-build-cache-

      # - name: Install packages from Homebrew
      #   run: |
      #     brew update
      #     brew install llvm || echo "clang already installed from cache"

      - name: Add Homebrew LLVM to PATH
        run: echo "$(brew --prefix llvm)/bin:$(brew --prefix coreutils)/bin" >> $GITHUB_PATH

      - run:  clang --version && cc --version

      - run:  timeout 3m arch -arm64  make PLATFORM=libc test-bootstrap-llvm
        continue-on-error: true      # TODO

      - run:  timeout 3m arch -arm64  make PLATFORM=posix test-bootstrap-llvm
        continue-on-error: true      # TODO

      - run:  timeout 3m arch -arm64  make PROFILER=1 PLATFORM=libc test-bootstrap-llvm
        continue-on-error: true      # TODO

      - run:  timeout 3m arch -arm64  make PROFILER=1 PLATFORM=posix test-bootstrap-llvm
        continue-on-error: true      # TODO

      - run:  timeout 3m arch -x86_64 make PLATFORM=libc TARGET_CPU=x86_64 test-bootstrap-x86
        continue-on-error: true      # TODO

      - run:  timeout 3m arch -x86_64 make PLATFORM=posix TARGET_CPU=x86_64 test-bootstrap-x86
        continue-on-error: true      # TODO

      - run:  timeout 3m arch -x86_64 make PROFILER=1 PLATFORM=libc TARGET_CPU=x86_64 test-bootstrap-x86
        continue-on-error: true      # TODO

      - run:  timeout 3m arch -x86_64 make PROFILER=1 PLATFORM=posix TARGET_CPU=x86_64 test-bootstrap-x86
        continue-on-error: true      # TODO

      - run:  timeout 3m make test-evaluator
        continue-on-error: true      # TODO

      - run:  timeout 3m make test-parser
        continue-on-error: true      # TODO

  build-linux-amd64-full-bootstrap:
    name: "linux x86_64 full bootstrap"
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/attila-lendvai/maru-ci:amd64
      options: --init

    steps:
      - name: System info
        run: |
          echo "===== OS Info ====="
          uname -a
          sw_vers || lsb_release -a || cat /etc/os-release || true
          echo "===== CPU Info ====="
          uname -m
          sysctl -n machdep.cpu.brand_string || lscpu || true
          echo "===== Environment ====="
          env

      - name: Calm down Git
        run: git config --global --add safe.directory /__w/maru/maru

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false

      - run:  clang --version && cc --version

      - run:  timeout 20m make test-bootstrap-recursively
